# permissions for end users to edit placementmanifestworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: placementmanifestwork-editor-role
rules:
- apiGroups:
  - cluster.open-cluster-management.io.my.domain
  resources:
  - placementmanifestworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io.my.domain
  resources:
  - placementmanifestworks/status
  verbs:
  - get
