# permissions for end users to view placementmanifestworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: placementmanifestwork-viewer-role
rules:
- apiGroups:
  - cluster.open-cluster-management.io.my.domain
  resources:
  - placementmanifestworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io.my.domain
  resources:
  - placementmanifestworks/status
  verbs:
  - get
