apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: work-placement
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: work-placement
subjects:
- kind: ServiceAccount
  name: work-placement
  namespace: open-cluster-management
